global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flaskapp'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['0.0.0.0:9100']