apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
- serviceAccount.yaml
- service.yaml
- volume.yaml
